### ISSUE TITLE
path: does not work

### ISSUE THREAD

**Issue by col-panic** [san-kumar/vue2-sidebar#1]
While I can open my routes using `href: /#/destination` - `path: /destination` does not work. It simply does not present it as selectable?!

**Comment by col-panic** [comment]
Is jquery required for path to work?

**Comment by col-panic** [comment]
It seems that the `path` parameter is not even considered in your source - is this really implemented?

**Comment by san-kumar** [comment]
hi, i think i implemented it using to="/test"
